import asyncio
import time
from typing import Any

from ...domain.exceptions import ProviderTimeoutException, ProviderUnavailableException
from ..models import LLMRequest, LLMResponse, calculate_cost
from .base import LLMProvider


class MockLLMProvider(LLMProvider):
    """
    Mock LLM provider for local development, deterministic offline pipelines,
    and resilience testing (timeouts, outages, fallbacks).
    """

    def __init__(
        self,
        provider_name: str = "mock_local",
        simulated_delay: float = 0.005,
    ):
        self._provider_name = provider_name
        self.simulated_delay = simulated_delay
        self.fail_models: set[str] = set()
        self.timeout_models: set[str] = set()
        self.custom_responses: dict[str, str] = {}
        self.call_count: int = 0
        self.invocations: list[dict[str, Any]] = []

    @property
    def provider_name(self) -> str:
        return self._provider_name

    def is_healthy(self) -> bool:
        return True

    def set_model_failure(self, model: str, should_fail: bool = True) -> None:
        """Configures model to simulate upstream provider 500/503 failure."""
        if should_fail:
            self.fail_models.add(model)
        else:
            self.fail_models.discard(model)

    def set_model_timeout(self, model: str, should_timeout: bool = True) -> None:
        """Configures model to simulate upstream gateway timeout."""
        if should_timeout:
            self.timeout_models.add(model)
        else:
            self.timeout_models.discard(model)

    async def generate(self, request: LLMRequest, model: str) -> LLMResponse:
        """Generates completion or triggers configured failure scenarios."""
        start_time = time.perf_counter()
        self.call_count += 1
        self.invocations.append({"model": model, "tenant_id": request.tenant_id, "prompt_len": len(request.prompt)})

        # 1. Simulate Timeout
        if model in self.timeout_models:
            # Sleep longer than the request timeout to trigger timeout handler
            await asyncio.sleep(request.timeout_seconds + 0.1)
            raise ProviderTimeoutException(
                provider=self.provider_name,
                model=model,
                timeout_seconds=request.timeout_seconds,
            )

        # 2. Simulate Provider Failure (503 / 500)
        if model in self.fail_models:
            await asyncio.sleep(self.simulated_delay)
            raise ProviderUnavailableException(
                provider=self.provider_name,
                model=model,
                reason="Simulated upstream provider connection drop (HTTP 503)",
            )

        # Normal execution
        if self.simulated_delay > 0:
            await asyncio.sleep(self.simulated_delay)

        # Generate realistic content
        if request.prompt in self.custom_responses:
            content = self.custom_responses[request.prompt]
        elif "summar" in request.prompt.lower():
            content = (
                f"Executive Summary for {request.tenant_id}: The analysis indicates stable operational liquidity, "
                "with Tier-1 regulatory capital adequacy above benchmarks and conservative tail risk exposures."
            )
        elif "var" in request.prompt.lower() or "risk" in request.prompt.lower():
            content = (
                "Financial Risk Assessment: Historical 10-day Value at Risk (99% confidence) is estimated at 2.45%. "
                "Stress scenario tests indicate maximum portfolio drawdown remains within defined mandates."
            )
        else:
            content = (
                f"Analysis response generated by {model} for tenant {request.tenant_id}. "
                "Factual evaluation confirms compliance with institutional investment guidelines."
            )

        # Token calculation: ~4 chars per token for prompt and response
        input_tokens = max(10, len(request.prompt) // 4 + (len(request.system_prompt or "") // 4))
        output_tokens = max(15, len(content) // 4)
        total_tokens = input_tokens + output_tokens

        latency_ms = (time.perf_counter() - start_time) * 1000.0
        cost_usd = calculate_cost(model, input_tokens, output_tokens)

        return LLMResponse(
            content=content,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=total_tokens,
            latency_ms=round(latency_ms, 2),
            estimated_cost_usd=cost_usd,
            model=model,
            provider=self.provider_name,
            request_id=request.request_id,
            tenant_id=request.tenant_id,
            prompt_version=request.prompt_version,
            cached=False,
            fallback_used=False,
            finish_reason="stop",
            metadata={"simulated": True},
        )
